### PR TITLE
fix: various validation related issues (resolves #1776, #1775, #1774, #1773, #1772)

### LINKED ISSUE #1772: Add meeting: Time error message
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When an error is triggered by the meeting start/end time not being in the proper format, it says this:
Screenshot 2023-06-07 at 12 52 36 PM

**To Reproduce**
1. Create an engagement
2. Fill in engagement details
3. Add meeting
4. Add an end or start time in an incorrect format
This is what I entered: 
Screenshot 2023-06-07 at 12 52 41 PM
5. Save
6. see error

**Expected behavior**
An error message that says, "The meeting [start/end] time format is not valid."

### LINKED ISSUE #1773: Add meeting: Invalid link format did not produce an error
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I add a link that's invalid for the link to join, it doesn't produce an error:
Screenshot 2023-06-07 at 12 52 55 PM

**To Reproduce**
1. Create an engagement
2. Fill in engagement details
3. Add a meeting
4. Enter an invalid format for the link to join under virtual - video call
5. Save
6. See lack of error

**Expected behavior**
Produce an error with an error message that's the same as on a member's page when they enter an invalid link format.

### LINKED ISSUE #1774: Create engagement: Selection criteria - intersectional
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When creating an engagement on the selection criteria page, if I select "yes" for intersectional but don't specify a group, this is the error I get:
Screenshot 2023-06-07 at 1 03 57 PM

**To Reproduce**
1. Create an engagement
2. Select "yes" under intersectional on the selection criteria page
3. don't select a specific intersectional identity in the dropdown
4. Save
5. see error

**Expected behavior**
Error message should be: "If you are looking for a group with a specific experience or identity, you must select which type of experience or identity you are looking for."

### LINKED ISSUE #1775: Engagement detail for survey: Fields don't have inline errors
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
The following fields don't trigger an inline error:
- Survey sent by date
- Survey due date
- Sign up deadline
- Languages (only if "add language" is pressed and the dropdown is revealed)
(There is an error message at the top of the page, though)

**To Reproduce**
1. Create an engagement that's a survey
2. Go to engagement details
3. Enter invalid dates for the fields above
4. Save
5. See error

**Expected behavior**
Inline error using the same copy that's in the error notification.

**Screenshots**
Screenshot 2023-06-07 at 1 15 54 PM
Screenshot 2023-06-07 at 1 15 59 PM
Screenshot 2023-06-07 at 1 16 04 PM
Screenshot 2023-06-07 at 1 20 17 PM
Screenshot 2023-06-07 at 1 20 34 PM

### LINKED ISSUE #1776: Engagement detail for survey: Language field error message
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
The error message for languages is not clear:
Screenshot 2023-06-07 at 1 20 17 PM

**To Reproduce**
1. Create an engagement that's a survey
2. Go to engagement details
3. Click "add language" but don't fill in the dropdown
4. Save
5. See error

**Expected behavior**
"Please select a language that the engagement documents will be in."

### PR DESCRIPTION
**Pull request by jobara**
Resolves #1776 
Resolves #1775 
Resolves #1774 
Resolves #1773 
Resolves #1772 

Additional Changes

- Adds IdentityType enum
- Adds LocationType enum
- Adds validation tests (See #1813) for some of the request types
- Addresses some runtime errors when invalid data passed to request
- Updates validation error messages
- Corrects some validation rules

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: app/Http/Requests/MeetingRequest.php [hunk 1]
```diff
@@ -109,23 +114,33 @@ public function attributes(): array
             'end_time' => __('meeting end time'),
             'date' => __('meeting date'),
             'timezone' => __('meeting time zone'),
+            'locality' => __('city or town'),
             'region' => __('province or territory'),
             'meeting_url' => __('link to join the meeting'),
-            'meeting_phone' => __('meeting phone number'),
+            'meeting_phone' => __('phone number to join the meeting'),
```
Comment (jobara) [inline app/Http/Requests/MeetingRequest.php:120]: @greatislander do you think something like this would still fit into the validation error message after being translated into French?

Comment (greatislander) [reply app/Http/Requests/MeetingRequest.php:120]: Yes, I think so.

File: app/Http/Requests/MeetingRequest.php [hunk 2]
```diff
@@ -109,23 +114,33 @@ public function attributes(): array
...
             'region.required' => __('You must enter a :attribute for the meeting location.'),
             'postal_code.required' => __('You must enter a :attribute for the meeting location.'),
             'meeting_software.required' => __('You must indicate the :attribute.'),
-            'meeting_url.required' => __('You must provide a :attribute.'),
+            'meeting_url.required' => __('You must enter a :attribute.'),
+            'meeting_phone.required' => __('You must enter a :attribute.'),
+            'start_time.required' => __('You must enter a :attribute'),
+            'start_time.date_format' => __('The :attribute format is not valid.'),
+            'start_time.before' => __('The :attribute must be before the :date.'),
+            'end_time.required' => __('You must enter a :attribute'),
```
Comment (greatislander) [inline app/Http/Requests/MeetingRequest.php:141]: I'm wondering the the attribute name will be "end time"— if so this is going to be ungrammatical ("enter a end time"). Same goes for "end date".

File: app/Http/Requests/SaveIndividualRolesRequest.php [hunk 3]
```diff
@@ -41,6 +41,8 @@ public function messages(): array
     {
         return [
             'roles.required' => __('You must select what you would like to do on the website.'),
+            'roles.array' => __('You must select what you would like to do on the website.'),
+            'roles.*.Illuminate\Validation\Rules\Enum' => __('You must select a valid role to perform on the website.'),
```
Comment (greatislander) [inline app/Http/Requests/SaveIndividualRolesRequest.php:45]: I've never seen this before— can you tell me a bit more about this rule type?

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 4]
```diff
@@ -295,19 +297,45 @@ public function attributes(): array
...
+            'materials_by_date.required' => __('You must enter a :attribute.'),
+            'materials_by_date.date' => __('Please enter a valid :attribute.'),
+            'materials_by_date.before' => __('The :attribute must be before the :date.'),
+            'complete_by_date.required' => __('You must enter a :attribute.'),
+            'complete_by_date.date' => __('Please enter a valid :attribute.'),
+            'complete_by_date.after' => __('The :attribute must be after the :date.'),
+            'signup_by_date' => __('You must enter a :attribute.'),
+            'signup_by_date.date' => __('Please enter a valid date for the :attribute.'),
+            'signup_by_date.before' => __('The :attribute must be before the :date.'),
+            'signup_by_date.before' => __('The :attribute must be before the :date.'),
```
Comment (greatislander) [inline app/Http/Requests/UpdateEngagementRequest.php]: See analysis issue above.

File: app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php [hunk 5]
```diff
@@ -72,19 +73,57 @@ public function rules(): array
...
+            'disability_types.*' => __('Disability or Deaf group'),
+            'ethnoracial_identities' => __('ethnoracial group'),
+            'ethnoracial_identities.*' => __('ethnoracial group'),
+            'first_languages' => __('first language'),
+            'first_languages.*' => __('first language'),
+            'gender_and_sexual_identities' => __('gender or sexual identity group'),
+            'gender_and_sexual_identities.*' => __('gender or sexual identity group'),
+            'ideal_participants' => __('ideal number of participants'),
+            'indigenous_identities' => __('indigenous group'),
+            'indigenous_identities.*' => __('indigenous group'),
```
Comment (greatislander) [inline app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php]: Indigenous should be capitalized, see (for example): https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-style-guide/writing-guide-for-indigenous-content/capitalization-and-formatting-of-indigenous-terms#capitalizing-Indigenous-terms

**Review by greatislander — CHANGES_REQUESTED** [review]

File: app/Http/Requests/MeetingRequest.php (hunk 2 above)
Comment (jobara) [reply app/Http/Requests/MeetingRequest.php:141]: There is an `attributes` section above with the following mappings:

```php
[
            'start_time' => __('meeting start time'),
            'end_time' => __('meeting end time'),
            'date' => __('meeting date'),
            'timezone' => __('meeting time zone'),
            'locality' => __('city or town'),
            'region' => __('province or territory'),
            'meeting_url' => __('link to join the meeting'),
            'meeting_phone' => __('phone number to join the meeting'),
]
```

File: app/Http/Requests/SaveIndividualRolesRequest.php (hunk 3 above)
Comment (jobara) [reply app/Http/Requests/SaveIndividualRolesRequest.php:45]: That's for when you need to set the message for an enum validation rule like `roles: [new Enum(IndividualRole::class)]`. It checks that the value is in the enum.

Comment (greatislander) [reply app/Http/Requests/SaveIndividualRolesRequest.php:45]: Ah, so this is how you set that attribute, good to know. I've used those Enum rules but never set the attribute. Thanks.

**Review by greatislander — APPROVED** [review]
Assuming the tests pass, I think this is ready to merge!
