### PR TITLE
feat: fix login route not defined, adopt Laravel >= 11 structure

### LINKED ISSUE #2635: Route [login] not defined.
**`Symfony\Component\Routing\Exception\RouteNotFoundException`**

Route [login] not defined.

🎯 Illuminate\Routing\UrlGenerator::route
🗂 /vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:516

```php
514      }
515   
516*     throw new RouteNotFoundException("Route [{$name}] not defined.");
517  }
518   
```
[Open in Flare](https://flareapp.io/errors/7147989/latest)

### PR DESCRIPTION
**Pull request by greatislander**
This PR restructures the application to Laravel >= 11 specifications to allow `$middleware->redirectGuestsTo` to be configured in `bootstrap/app.php`.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by jobara** [comment]
@greatislander could you bring this up-to-date with the dev branch. There have been some dependency PRs merged since. Locally I'm running into a merge conflict on composer.lock file as well.

**Comment by greatislander** [comment]
@jobara Updated. I also removed the `trustedHosts` middleware as it seemed to be causing problems and may no longer be needed. I haven't noticed any issues but please let me know if you do.

File: config/database.php [hunk 1]
```diff
@@ -1,147 +1,8 @@
...
-            'charset' => 'utf8mb4',
-            'collation' => 'utf8mb4_unicode_ci',
-            'prefix' => '',
-            'prefix_indexes' => true,
-            'strict' => true,
-            'engine' => null,
-            'options' => extension_loaded('pdo_mysql') ? array_filter([
-                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
-            ]) : [],
-        ],
```
Comment (jobara) [inline config/database.php:64]: Did this get moved somewhere or is it no longer needed?

**Review by jobara — CHANGES_REQUESTED** [review]
I've run into an issue regarding languages. I logged in as an individual user and went to the language preferences. I change the website language to LSQ. That was all fine, but after logging out and logging back in again, the site language was in English. If went back to the language settings page, it would switch back to LSQ.

File: config/database.php (hunk 1 above)
Comment (greatislander) [reply config/database.php:64]: Basically in Laravel 11 you don't need to include any default values for config that are unchanged. So I tried to clean up our configs a bit for readability.

**Comment by greatislander** [comment]
> I've run into an issue regarding languages. I logged in as an individual user and went to the language preferences. I change the website language to LSQ. That was all fine, but after logging out and logging back in again, the site language was in English. If went back to the language settings page, it would switch back to LSQ.

I see this same behaviour on the dev branch locally. I'm wondering if it's a regression that was introduced elsewhere but not observed yet?

**Comment by jobara** [comment]
> > I've run into an issue regarding languages. I logged in as an individual user and went to the language preferences. I change the website language to LSQ. That was all fine, but after logging out and logging back in again, the site language was in English. If went back to the language settings page, it would switch back to LSQ.
> 
> I see this same behaviour on the dev branch locally. I'm wondering if it's a regression that was introduced elsewhere but not observed yet?

It seems this is related to the login links. I've filed a new issue; #2651.

**Review by jobara — APPROVED** [review]
