### PR TITLE
fix: can change route_has_params in admin panel (resolves #1482)

### LINKED ISSUE #1482: Missing required parameter for [Route: en.individuals.edit] [URI: en/individuals/{individual}/edit]...
**`Illuminate\Routing\Exceptions\UrlGenerationException`**

Missing required parameter for [Route: en.individuals.edit] [URI: en/individuals/{individual}/edit] [Missing parameter: individual].

:dart: Illuminate\Routing\Exceptions\UrlGenerationException::forMissingParameters
:page_facing_up: /app/vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php

```php
33          $message .= '.';
34  
35*         return new static($message);
36      }
37  }
```
[Open in Flare](https://flareapp.io/errors/3006589/latest)

### PR DESCRIPTION
**Pull request by jobara**
Resolves #1482 

Disables the Route Has Params toggle from the sign language interpretations edit interface in the admin panel. This is so that someone can see what the state is, but not accidentally alter it into something that is broken.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: app/Filament/Resources/InterpretationResource/Pages/EditInterpretation.php [hunk 1]
```diff
@@ -16,4 +17,31 @@ protected function getActions(): array
...
+            Forms\Components\TextInput::make('name')
+                ->required()
+                ->maxLength(255)
+                ->columnSpan(2),
+            Forms\Components\TextInput::make('route')
+                ->required()
+                ->maxLength(255),
+            Forms\Components\TextInput::make('namespace')
+                ->maxLength(255),
+            Forms\Components\Toggle::make('route_has_params')
```
Comment (chosww) [inline app/Filament/Resources/InterpretationResource/Pages/EditInterpretation.php]: Could we potentially comment out this part and put it back later when we need the option?

Comment (jobara) [reply app/Filament/Resources/InterpretationResource/Pages/EditInterpretation.php]: I left it there but disabled it so that we could present the state in the UI without making it interactive, but I guess we could remove it as well.

**Review by chosww — APPROVED** [review]
