### PR TITLE
fix: dropdown search in AttachAction/AssociateAction returns no results. (resolves #3029)

### LINKED ISSUE #3029: Dropdown search in AttachAction/AssociateAction returns no results.
### Prerequisites

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

Admin is unable to attach a resource collection to a library. This issue occurs when there are many resource collections and the desired one is not available in the preloaded dropdown. When opening a library to attach a specific resource collection, searching for it shows a “No results found” message, even if the resource collection is available in the dropdown.

Similarly, the admin is unable to associate any Documents added to the platform with Tools. When searching for a specific document (whether newly created or already existing), the search results show a “No results found” message.

### To Reproduce

**Adding a Resource Collection**

1. Go to Admin (Dashboard) → Pages, Resources and Training → Resource Collections.
2. Add a new resource collection.

**Attaching a Resource Collection to a Library**

1. Go to Admin (Dashboard) → Pages, Resources and Training → Libraries.
2. Edit an existing Library or create a new one.
3. Click Edit to attach a resource collection.
4. Search the dropdown for the newly created resource collection or any existing one.
5. The search field displays “No results” **(error)**.

**Creating a Document**

1. Go to Admin (Dashboard) → Pages, Resources and Training → Documents.
2. Create a Document.

**Associating a Document to a Tool**

1. Go to Admin (Dashboard) → Pages, Resources and Training → Tools.
2. Edit an existing Tool or create a new one.
3. Click Edit to associate a Document.
4. Search the dropdown for the newly created Document or any existing one.
5. The search field displays “No results” **(error)**.

### Expected behavior

The **Resource Collections** and **Documents** that are available should be searchable. 

### Screenshots

**Error:** Unable to Resource collection to a Library

Image

when searching for **Principles of Screen Reader Support (1)** which already exists, gives **no result found** message.

Image

**Error:** Documents cannot be added to a Tool 

Image

When searching for **Doc 2** which already exists, gives **no result found** message.

Image

### Details

- Device:
- Operating system:
- Browser:
- Link to affected page:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rvs1212**
- Added forceSearchCaseInsensitive() to AttachAction and AssociateAction to resolve dropdown search returning no results.

Resolves #3029 

### Description
Dropdown search in AttachAction and AssociateAction returns no results when record titles have mixed casing. Added `forceSearchCaseInsensitive()` to ensure search works regardless of case and sorting by `created_at` `desc` to show newest records first in the dropdown.

### Changes
- Added `forceSearchCaseInsensitive()` to AssociateAction in `DocumentsRelationManager`
- Added `forceSearchCaseInsensitive()` to AttachAction in `ResourceCollectionsRelationManager`
- Added `recordSelectOptionsQuery()` to sort records by newest first in both relation managers

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: app/Filament/Resources/Tools/RelationManagers/DocumentsRelationManager.php [hunk 1]
```diff
@@ -23,7 +23,11 @@ public function table(Table $table): Table
             ])
             ->filters([])
             ->headerActions([
-                AssociateAction::make()->preloadRecordSelect()->associateAnother(false),
+                AssociateAction::make()
+                    ->preloadRecordSelect()
+                    ->associateAnother(false)
```
Comment (jobara) [inline app/Filament/Resources/Tools/RelationManagers/DocumentsRelationManager.php:28]: Is there a specific reason for removing the associate another option? It's possible that a tool will have multiple documents such as a spreadsheet and documentation file.

Comment (rvs1212) [reply app/Filament/Resources/Tools/RelationManagers/DocumentsRelationManager.php:28]: I have not changed that part, associateAnother was set to `false`, assuming that's the way it was designed to be handled.

Comment (jobara) [reply app/Filament/Resources/Tools/RelationManagers/DocumentsRelationManager.php:28]: Sorry, I missed that it was already there. Thanks for the clarification.

**Review by jobara — APPROVED** [review]
