### PR TITLE
fix: pagination for resource collection in a library is missing (resolves #2960)

### LINKED ISSUE #2960: Pagination for resource collection in a library is missing
### Prerequisites

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

Libraries will only display at most 10 resource collections, even if more are added. However, there should be pagination to show the remaining resources. 

### To Reproduce

1. Login as an admin an add more than 10 resource collections to a library
2. View the library
3. Notice that only 10 are added, but there is no pagination

### Expected behavior

Pagination should be displayed to show the additional resource collection in the library.

see: R[esource Library wireframe](https://www.figma.com/design/5J9uimqjouSxBJW6JR6uZl/Wireframes?node-id=1664-12916&t=XvnWhjHymVd2n9FD-4)

### Screenshots

screenshot showing only 10 resource collections displayed in the library
screenshot showing that the library has 21 resource collections attached

### Details

- Device:
- Operating system:
- Browser:
- Link to affected page:

### Additional context

Will likely need to look at Livewire's [Multiple Paginators documentation](https://livewire.laravel.com/docs/pagination#multiple-paginators) as there are at least 2 that would appear on this page.

### PR DESCRIPTION
**Pull request by jobara**
Resolves #2960 

- Paginates the resource collections
- Sets the page name for the resource collections and resources pagenators 

_**NOTE:** This PR includes changes from #2965. That PR should be merged first and this PR updated from `dev`_

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: app/Livewire/LibraryResources.php [hunk 1]
```diff
@@ -58,7 +58,8 @@ public function search()
     public function render()
     {
         return view('livewire.library-resources', [
-            'resourceCollections' => $this->library->resourceCollections,
+            'resourceCollections' => $this->library->resourceCollections
+                ->paginate(10, pageName: 'collections-page'),
```
Comment (jobara) [inline app/Livewire/LibraryResources.php]: @greatislander do you think these query parameters need to be localized?

Comment (greatislander) [reply app/Livewire/LibraryResources.php]: Yes ideally they should be. There are lots of URLs which haven't been localized but when we add new ones we should take the opportunity to localize them.

**Review by greatislander — APPROVED** [review]
