### PR TITLE
fix: date picker improvements

### LINKED ISSUE #1311: Date picker bugs
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
- The “day” is pre-populated with "undefined". If I click into it, it doesn’t disappear and I can’t type anything. (However, if I tab into it and it selects the “undefined”, I can edit it). The only way to get rid of it is to click/focus in, and then click out - then it disappears

Screen Shot 2022-11-15 at 3 58 16 PM

### PR DESCRIPTION
**Pull request by greatislander**
- if value is null, set y/m/d to empty strings
- remove minimum year attributes

Hasn't addressed #1311 as I can't reproduce, but if I can figure out what's happening there I will add the changes to this PR.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: resources/js/datePicker.js [hunk 1]
```diff
@@ -8,9 +8,9 @@ export default (initial = "") => ({
     init() {
         this.date = initial;
         let [y, m, d] = this.date.split("-");
-        this.year = y;
-        this.month = m;
-        this.day = d;
+        this.year = y ?? "";
+        this.month = m ?? "";
+        this.day = d ?? "";
```
Comment (jobara) [inline resources/js/datePicker.js]: FOr the destructing assignment, I think you can actually set a default value. Something like:

```javascript
let [y = "", m = "", d = ""] = this.date.split("-");
```

and if so, I wonder if you could then actually do:

```javascript
[this.year = "", this.month = "", this.day =""] = this.date.split("");
```

It isn't a big deal either way though, so what is here is fine too.

Comment (greatislander) [reply resources/js/datePicker.js]: Oh I'll try that— good call, @jobara.

Comment (greatislander) [reply resources/js/datePicker.js]: You can't do the second one (destructuring to `this.year` etc). But your first example works!

**Review by jobara — APPROVED** [review]
