### PR TITLE
fix: display social medias' invalid url error message in-line

### LINKED ISSUE #641: Error messages for social media links should appear near the field
When creating an individual page if I use an incorrect format for a social media link then I get an error message but it's only in the aggregated messages at the top.

### PR DESCRIPTION
**Pull request by chosww**
Resolves issue #641.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: app/Http/Requests/UpdateIndividualRequest.php [hunk 1]
```diff
@@ -68,4 +68,16 @@ public function attributes(): array
...
+
+    /**
+     * Get the error messages for the defined validation rules.
+     *
+     * @return array
+     */
+    public function messages()
+    {
+        return [
+            'social_links.*.active_url' => __('You must enter valid url.'),
```
Comment (greatislander) [inline app/Http/Requests/UpdateIndividualRequest.php]: It should probably say "a valid website address".

**Review by greatislander — CHANGES_REQUESTED** [review]

**Review by greatislander — APPROVED** [review]
