### PR TITLE
fix: not able to add Resource to a Resource Collection (resolves #3025)

### LINKED ISSUE #3025: Not able to add Resource to a Resource Collection
### Prerequisites

- [ ] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

Admin is unable to add or attach a resource to a resource collection. This issue occurs when a large number of resources have been added to the platform. When opening a resource collection to attach a specific resource, the resource does not appear in the dropdown list or search results.

### To Reproduce

**Adding a Resource** 
1. Go to Admin (Dashboard) → Pages, Resources and Training → Resources. 
2. Add a new resource. 

**Attaching a Resource to a Resource Collection** 
1. Go to Admin (Dashboard) → Pages, Resources and Training → Resource Collections. 
2. Edit an existing resource collection or create a new one. 
3. Click Edit to attach a resource. 
4. Search the dropdown for the newly created resource. 
5. The search field displays “No results” **(error)**. 

**Note:** This issue appears to occur when the total number of resources exceeds 50.

### Expected behavior

Resources that are added under `Resources` section should be able to be attached to a `Resource Collection`.

### Screenshots

Image

Image

### Details

- Device:
- Operating system:
- Browser:
- Link to affected page:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rvs1212**
Fix to resolve the issue where resources are not able to be attached to a resource collection, along with sorting the preloaded list.

Resolves #3025 

### Changes
- Added `forceSearchCaseInsensitive()` to fix case-sensitive search 
- Changed sorting by `created_at desc` to show newest resources first in the dropdown

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

File: app/Filament/Resources/ResourceCollections/RelationManagers/ResourcesRelationManager.php [hunk 1]
```diff
@@ -37,7 +37,10 @@ public function table(Table $table): Table
             ])
             ->filters([])
             ->headerActions([
-                AttachAction::make()->preloadRecordSelect(),
+                AttachAction::make()
+                    ->preloadRecordSelect()
+                    ->recordSelectOptionsQuery(fn ($query) => $query->orderBy('title->'.locale()))
+                    ->recordSelectSearchColumns(['title->en', 'title->fr']),
```
Comment (jobara) [inline app/Filament/Resources/ResourceCollections/RelationManagers/ResourcesRelationManager.php]: I'm not seeing `recordSelectSearchColumns` having an effect here. By default it should be using the `recordTitle` which is set to the localized title already. 

See: https://filamentphp.com/docs/4.x/resources/managing-relationships#searching-the-options-to-attach-across-multiple-columns

**Review by jobara — CHANGES_REQUESTED** [review]
The sorting does work, however overall the changes do not seem to address the actual issue. I'm still noticing a limit of 50 items in the select and cannot search for all of the resources.

## Example

The resource called "xx" is not available in the resource list.

xx resource missing from select

However, I am able to search for it.

can search for resource xx

The resource titled "Third" is in the list.

Third resource is available in the select

However I am not able to search for it.

Image

## Select limit

By default the select has a limit of 50 items. 

See: https://filamentphp.com/docs/4.x/forms/select#limiting-the-number-of-options 

If you'd like to change this you can customize the select field with `recordSelect`

see: https://filamentphp.com/docs/4.x/resources/managing-relationships#customizing-the-select-field-in-the-attached-modal

The thing to note is that having a large limit may affect performance. So that's something to consider. Do you want to only preload a subset of the available resources and if so which? This would require searching for any that aren't displayed in the select.

If you want to show all of the Resources in the select you could do the following:

```php
->recordSelect(
  fn(Select $select) => $select->optionsLimit(Resource::count())
)
```

Here I'm customizing the select by setting the `optionsLimit` to be the count of available resources. I believe this is updated on page load, so you should be able to add new resources and see them in the list on the next page load of the resource collection.

## Case insensitive search

Instead of using `recordSelectionSearchColumns` make the search case insensitive by using `forceSearchCaseInsensitive(true)`. 

see: https://github.com/filamentphp/filament/discussions/15665#discussioncomment-12287999

File: app/Filament/Resources/ResourceCollections/RelationManagers/ResourcesRelationManager.php (hunk 1 above)
Comment (rvs1212) [reply app/Filament/Resources/ResourceCollections/RelationManagers/ResourcesRelationManager.php]: Yes, I kept the default preload limit of 50 results instead of loading all resources to avoid potential performance issues. I initially added sorting to make the resources easier to find, but realized it would be more effective to display the newest resources first. I updated the sorting so that the most recently added resources appear at the top of the dropdown, making them easier to locate.

**Review by jobara — APPROVED** [review]
