### PR TITLE
fix: localize attributes properly

### LINKED ISSUE #2011: Attribute names in validation messages are not localized
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

In some validation error messages the name of the field is interpolated as the `:attribute`. These attributes all need to be localized and cannot just rely on falling back to the fields name.

See: https://laravel.com/docs/10.x/validation#specifying-custom-attribute-values

**Expected behavior**

Validation error messages are completely localized.

**Screenshots**

meeting types not localized
Screenshot of error message with meeting types not localized

e-mail not localized
Screenshot of error message with email

### PR DESCRIPTION
**Pull request by chosww**
Resolves #2011. 

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by chosww** [comment]
@jobara I think the meeting types error is the one like UpdateProjectRequest; the ones don't use :attribute explicitly. I didn't find any use cases of :attribute for meeting_types, could you tell me in which workflow you got that error message please?

**Comment by jobara** [comment]
> @jobara I think the meeting types error is the one like UpdateProjectRequest; the ones don't use :attribute explicitly. I didn't find any use cases of :attribute for meeting_types, could you tell me in which workflow you got that error message please?

I believe it's coming from the [validation.required](https://github.com/accessibility-exchange/platform/blob/666fb6854ba2abc8fc9298464eed5722136b4fc1/resources/lang/fr/validation.php#L102) text. It's likely the case that a required meeting_types field is empty. An example would be from [UpdateIndividualCommunicationAndConsultationPreferencesRequest](https://github.com/accessibility-exchange/platform/blob/666fb6854ba2abc8fc9298464eed5722136b4fc1/app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php#L43) validation. 

My feeling at the moment is that any validated field should have a localized attribute name specified. This would prevent errors if we removed an overridden message, or didn't override one that became needed later (e.g. changed the validation rules).

**Comment by jobara** [comment]
Tests will be expanded with #1813

**Comment by jobara** [comment]
@chosww could you please run `php artisan localize` and commit the updates?

File: app/Http/Requests/MeetingRequest.php [hunk 1]
```diff
@@ -113,11 +113,20 @@ public function attributes(): array
...
             'meeting_url' => __('link to join the meeting'),
             'meeting_phone' => __('phone number to join the meeting'),
+            'meeting_software' => __('meeting software'),
+            'alternative_meeting_software' => __('alternative meeting software'),
+            'additional_video_information' => __('additional video information'),
+            'additional_phone_information' => __('additional phone information'),
+            'meeting_types' => __('meeting types'),
+            'street_address' => __('Street address'),
+            'postal_code' => __('Postal code'),
+            'unit_suite_floor' => __('Unit, suite, or floor'),
```
Comment (jobara) [inline app/Http/Requests/MeetingRequest.php:129]: Add

```php
[
    'title.en' => __('meeting title (English)'),
    'title.fr' => __('meeting title (French)'),
    'title.*' => __('meeting title'),
    'meeting_types.*' => __('ways to attend'),
]
```

Modify

```php
[
    'meeting_types' => __('ways to attend'),
]

File: app/Http/Requests/SaveOrganizationRolesRequest.php [hunk 2]
```diff
@@ -21,6 +21,13 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'roles' => __('roles'),
+        ];
+    }
```
Comment (jobara) [inline app/Http/Requests/SaveOrganizationRolesRequest.php]:
```suggestion
    public function attributes(): array
    {
        return [
            'roles' => __('roles'),
            'roles.*' => __('roles'),
        ];
    }
```

File: app/Http/Requests/SaveUserLanguagesRequest.php [hunk 3]
```diff
@@ -30,6 +30,17 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'locale' => __('locale'),
```
Comment (jobara) [inline app/Http/Requests/SaveUserLanguagesRequest.php]:
```suggestion
            'locale' => __('website language'),
```

File: app/Http/Requests/SaveIndividualRolesRequest.php [hunk 4]
```diff
@@ -34,6 +34,13 @@ public function prepareForValidation()
         request()->mergeIfMissing($fallbacks);
     }
 
+    public function attributes(): array
+    {
+        return [
+            'roles' => __('You must select what you would like to do on the website.'),
+        ];
+    }
```
Comment (jobara) [inline app/Http/Requests/SaveIndividualRolesRequest.php]: It looks like you copied the message here instead of adding the attribute value.

```suggestion
    public function attributes(): array
    {
        return [
            'roles' => __('roles'),
            'roles.*' => __('roles'),
        ];
    }
```

File: app/Http/Requests/MeetingRequest.php (hunk 1 above)
Comment (jobara) [inline app/Http/Requests/MeetingRequest.php]:
```suggestion
            'title.en' => __('meeting title (English)'),
            'title.fr' => __('meeting title (French)'),
            'title.*' => __('meeting title'),
            'start_time' => __('meeting start time'),
            'end_time' => __('meeting end time'),
            'date' => __('meeting date'),
            'directions' => __('directions'),
            'timezone' => __('meeting time zone'),
            'locality' => __('city or town'),
            'region' => __('province or territory'),
            'meeting_url' => __('link to join the meeting'),
            'meeting_phone' => __('phone number to join the meeting'),
            'meeting_software' => __('meeting software'),
            'alternative_meeting_software' => __('alternative meeting software'),
            'additional_video_information' => __('additional video information'),
            'additional_phone_information' => __('additional phone information'),
            'meeting_types' => __('ways to attend'),
            'meeting_types.*' => __('ways to attend'),
            'street_address' => __('Street address'),
            'postal_code' => __('Postal code'),
            'unit_suite_floor' => __('Unit, suite, or floor'),
```

File: app/Http/Requests/StoreDefinedTermRequest.php [hunk 5]
```diff
@@ -28,4 +28,12 @@ public function rules()
             'definition.*' => 'nullable|string',
         ];
     }
+
+    public function attributes(): array
```
Comment (jobara) [inline app/Http/Requests/StoreDefinedTermRequest.php:32]: I don't think this file is used anymore. I think we can delete it. Can you confirm?

File: app/Http/Requests/StoreEngagementRecruitmentRequest.php [hunk 6]
```diff
@@ -22,4 +22,11 @@ public function rules(): array
             ],
         ];
     }
+
+    public function attributes(): array
+    {
+        return [
+            'recruitment' => __('recruitment'),
```
Comment (jobara) [inline app/Http/Requests/StoreEngagementRecruitmentRequest.php]:
```suggestion
            'recruitment' => __('recruitment method'),
```

File: app/Http/Requests/StoreEngagementRequest.php [hunk 7]
```diff
@@ -25,6 +25,15 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'project_id' => __('project id'),
+            'name' => __('engagement name'),
+            'who' => __('who'),
+        ];
```
Comment (jobara) [inline app/Http/Requests/StoreEngagementRequest.php]:
```suggestion
        return [
            'project_id' => __('project id'),
            'name.en' => __('engagement name (English)'),
            'name.fr' => __('engagement name (French)'),
            'name.*' => __('engagement name'),
            'who' => __('who'),
        ];
```

File: app/Http/Requests/StoreOrganizationTypeRequest.php [hunk 8]
```diff
@@ -28,6 +28,13 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'type' => __('organization type'),
+        ];
```
Comment (jobara) [inline app/Http/Requests/StoreOrganizationTypeRequest.php:35]:
```suggestion
        return [
            'type' => __('organization type'),
            'name.en' => __('organization name (English)'),
            'name.fr' => __('organization name (French)'),
        ];
```

File: app/Http/Requests/StoreProjectContextRequest.php [hunk 9]
```diff
@@ -19,6 +19,14 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'context' => __('project context'),
+            'ancestor' => __('previous project'),
```
Comment (jobara) [inline app/Http/Requests/StoreProjectContextRequest.php:26]: Here's another idea, although I don't know which is better really.
```suggestion
            'ancestor' => __('original project'),
```

File: app/Http/Requests/StoreProjectRequest.php [hunk 10]
```diff
@@ -44,6 +44,16 @@ public function rules()
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'projectable_type' => __('projectable type'),
+            'projectable_id' => __('projectable id'),
+            'ancestor_id' => __('previous project id'),
+            'name' => __('project name'),
```
Comment (jobara) [inline app/Http/Requests/StoreProjectRequest.php]:
```suggestion
            'name.en' => __('project name (English)'),
            'name.fr' => __('project name (French)'),
            'name.*' => __('project name'),
```

File: app/Http/Requests/StoreQuizResultRequest.php [hunk 11]
```diff
@@ -31,6 +31,13 @@ public function rules()
         return $rules;
     }
 
+    public function attributes(): array
+    {
+        return [
+            'questions' => __('questions'),
```
Comment (jobara) [inline app/Http/Requests/StoreQuizResultRequest.php]:
```suggestion
            'questions.*' => __('questions'),
```

File: app/Http/Requests/StoreRegulatedOrganizationRequest.php [hunk 12]
```diff
@@ -20,6 +20,14 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'type' => __('organization type'),
+            'name' => __('organization name'),
```
Comment (jobara) [inline app/Http/Requests/StoreRegulatedOrganizationRequest.php]:
```suggestion
            'name.en' => __('organization name (English)'),
            'name.fr' => __('organization name (French)'),
            'name.*' => __('organization name'),
```

File: app/Http/Requests/UpdateAccessNeedsRequest.php [hunk 13]
```diff
@@ -160,6 +160,29 @@ public function withValidator(Validator $validator)
         }
     }
 
+    public function attributes(): array
+    {
+        return [
+            'general_access_needs' => __('General access needs'),
```
Comment (jobara) [inline app/Http/Requests/UpdateAccessNeedsRequest.php:166]:
```suggestion
            'general_access_needs' => __('General access needs'),
            'general_access_needs.*' => __('General access needs'),
```

File: app/Http/Requests/UpdateAccessNeedsRequest.php [hunk 14]
```diff
@@ -160,6 +160,29 @@ public function withValidator(Validator $validator)
...
+            'other' => __('other'),
+            'other_access_need' => __('other access need'),
+            'meeting_access_needs' => __('meeting access needs'),
+            'signed_language_for_interpretation' => __('Signed language for interpretation'),
+            'spoken_language_for_interpretation' => __('Spoken language interpretation'),
+            'in_person_access_needs' => __('in person access needs'),
+            'document_access_needs' => __('document access needs'),
```
Comment (jobara) [inline app/Http/Requests/UpdateAccessNeedsRequest.php]:
```suggestion
            'in_person_access_needs' => __('in person access needs'),
            'in_person_access_needs.*' => __('in person access needs'),
            'document_access_needs' => __('document access needs'),
            'document_access_needs.*' => __('document access needs'),
```

File: app/Http/Requests/UpdateAreasOfInterestRequest.php [hunk 15]
```diff
@@ -21,6 +21,14 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'sectors' => __('Sectors'),
+            'impacts' => __('areas of impact'),
```
Comment (jobara) [inline app/Http/Requests/UpdateAreasOfInterestRequest.php]:
```suggestion
            'sectors' => __('Regulated Organization type'),
            'sectors.*' => __('Regulated Organization type'),
            'impacts' => __('area of accessibility planning and design'),
            'impacts.*' => __('area of accessibility planning and design'),
```

File: app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php [hunk 16]
```diff
@@ -53,6 +53,23 @@ public function rules(): array
...
+    {
+        return [
+            'preferred_contact_person' => __('preferred contact person'),
+            'email' => __('email'),
+            'phone' => __('phone'),
+            'vrs' => __('vrs'),
+            'support_person_name' => __('My support person’s name'),
+            'support_person_email' => __('My support person’s email'),
+            'support_person_phone' => __('My support person’s phone number'),
+            'support_person_vrs' => __('My support person requires Video Relay Service (VRS) for phone calls'),
```
Comment (jobara) [inline app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php]:
```suggestion
            'support_person_name' => __('support person’s name'),
            'support_person_email' => __('support person’s email'),
            'support_person_phone' => __('support person’s phone number'),
            'support_person_vrs' => __('support person requires Video Relay Service (VRS) for phone calls'),
```

File: app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php [hunk 17]
```diff
@@ -53,6 +53,23 @@ public function rules(): array
...
+            'preferred_contact_method' => __('preferred contact method'),
+            'consulting_methods' => __('consulting methods'),
+            'meeting_types' => __('meeting types'),
```
Comment (jobara) [inline app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php]:
```suggestion
            'consulting_methods' => __('consulting methods'),
            'consulting_methods.*' => __('consulting methods'),
            'meeting_types' => __('meeting types'),
            'meeting_types.*' => __('meeting types'),
```

File: app/Http/Requests/UpdateDefinedTermRequest.php [hunk 18]
```diff
@@ -28,4 +28,12 @@ public function rules()
             'definition.*' => 'nullable|string',
         ];
     }
+
+    public function attributes(): array
```
Comment (jobara) [inline app/Http/Requests/UpdateDefinedTermRequest.php:32]: It doesn't appear that this file is used anymore. Can it be removed?

File: app/Http/Requests/UpdateEngagementLanguagesRequest.php [hunk 19]
```diff
@@ -21,4 +21,11 @@ public function rules(): array
             ],
         ];
     }
+
+    public function attributes(): array
+    {
+        return [
+            'languages' => __('languages'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementLanguagesRequest.php:28]:
```suggestion
            'languages' => __('languages'),
            'languages.*' => __('languages'),
```

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 20]
```diff
@@ -276,6 +276,7 @@ public function attributes(): array
             'window_end_date' => __('end date'),
             'window_start_time' => __('start time'),
             'window_end_time' => __('end time'),
+            'window_flexibility' => __('window flexibility'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementRequest.php:279]:
```suggestion
            'window_flexibility' => __('window flexibility'),
            'weekday_availabilities' => __('availability'),
```

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 21]
```diff
@@ -287,10 +288,24 @@ public function attributes(): array
             'region' => __('province or territory'),
             'meeting_url' => __('link to join the meeting'),
             'meeting_phone' => __('phone number to join the meeting'),
+            'meeting_software' => __('meeting software'),
+            'meeting_types' => __('meeting types'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementRequest.php]:
```suggestion
            'meeting_types' => __('meeting types'),
            'meeting_types.*' => __('meeting types'),
```

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 22]
```diff
@@ -287,10 +288,24 @@ public function attributes(): array
...
+            'street_address' => __('Street address'),
+            'accepted_formats' => __('accepted formats'),
+            'other_accepted_formats' => __('other accepted formats'),
+            'timezone' => __('timezone'),
+            'unit_suite_floor' => __('Unit, suite, or floor'),
+            'directions' => __('directions'),
+            'alternative_meeting_software' => __('alternative meeting software'),
+            'additional_video_information' => __('additional video information'),
+            'additional_phone_information' => __('additional phone information'),
+            'document_languages' => __('document languages'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementRequest.php:312]:
```suggestion
            'document_languages' => __('document languages'),
            'document_languages.*' => __('document languages'),
```

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 23]
```diff
@@ -287,10 +288,24 @@ public function attributes(): array
...
             'meeting_phone' => __('phone number to join the meeting'),
+            'meeting_software' => __('meeting software'),
+            'meeting_types' => __('meeting types'),
             'materials_by_date' => __('date for materials to be sent by'),
             'complete_by_date' => __('due date'),
+            'postal_code' => __('Postal code'),
             'signup_by_date' => __('sign up deadline'),
-            'other_accepted_formats' => __('accepted formats'),
+            'street_address' => __('Street address'),
+            'accepted_formats' => __('accepted formats'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementRequest.php:300]:
```suggestion
            'accepted_formats' => __('accepted formats'),
            'accepted_formats.*' => __('accepted formats'),
```

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 24]
```diff
@@ -287,10 +288,24 @@ public function attributes(): array
...
+            'other_accepted_formats' => __('other accepted formats'),
+            'timezone' => __('timezone'),
+            'unit_suite_floor' => __('Unit, suite, or floor'),
+            'directions' => __('directions'),
+            'alternative_meeting_software' => __('alternative meeting software'),
+            'additional_video_information' => __('additional video information'),
+            'additional_phone_information' => __('additional phone information'),
+            'document_languages' => __('document languages'),
+            'open_to_other_formats' => __('open to other formats'),
+            'paid' => __('paid'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementRequest.php:315]:
```suggestion
            'paid' => __('paid'),
            'name.en' => __('engagement name (English)'),
            'name.fr' => __('engagement name (French)'),
            'name.*' => __('engagement name'),
            'description.en' => __('engagement description (English)'),
            'description.fr' => __('engagement description (French)'),
            'description.*' => __('engagement description'),
```

File: app/Http/Requests/UpdateEngagementRequest.php [hunk 25]
```diff
@@ -287,10 +288,24 @@ public function attributes(): array
...
+            'meeting_software' => __('meeting software'),
+            'meeting_types' => __('meeting types'),
             'materials_by_date' => __('date for materials to be sent by'),
             'complete_by_date' => __('due date'),
+            'postal_code' => __('Postal code'),
             'signup_by_date' => __('sign up deadline'),
-            'other_accepted_formats' => __('accepted formats'),
+            'street_address' => __('Street address'),
+            'accepted_formats' => __('accepted formats'),
+            'other_accepted_formats' => __('other accepted formats'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementRequest.php:302]:
```suggestion
            'other_accepted_formats' => __('other accepted formats'),
            'other_accepted_format' => __('other accepted format'),
            'other_accepted_format.en' =>  __('other accepted format (English)'),
            'other_accepted_format.fr' => __('other accepted format (French)'),
```

File: app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php [hunk 26]
```diff
@@ -76,6 +76,12 @@ public function rules(): array
     public function attributes(): array
     {
         return [
+            'location_type' => __('location type'),
+            'regions' => __('province or territory'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php:80]:
```suggestion
            'regions' => __('province or territory'),
            'regions.*' => __('province or territory'),
```

File: app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php [hunk 27]
```diff
@@ -76,6 +76,12 @@ public function rules(): array
...
+            'locations' => __('Location'),
```
Comment (jobara) [inline app/Http/Requests/UpdateEngagementSelectionCriteriaRequest.php:82]:
```suggestion
            'locations' => __('Location'),
            'locations.*.region' => __('location province or territory'),
            'locations.*.locality' => __('location city or town'),
```

File: app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php [hunk 28]
```diff
@@ -45,6 +45,22 @@ public function rules(): array
...
+    {
+        return [
+            'preferred_contact_person' => __('preferred contact person'),
+            'email' => __('email'),
+            'phone' => __('phone'),
+            'vrs' => __('vrs'),
+            'support_person_name' => __('My support person’s name'),
+            'support_person_email' => __('My support person’s email'),
+            'support_person_phone' => __('My support person’s phone number'),
+            'support_person_vrs' => __('My support person requires Video Relay Service (VRS) for phone calls'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php]:
```suggestion
            'support_person_name' => __('support person’s name'),
            'support_person_email' => __('support person’s email'),
            'support_person_phone' => __('support person’s phone number'),
            'support_person_vrs' => __('support person requires Video Relay Service (VRS) for phone calls'),
```

File: app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php [hunk 29]
```diff
@@ -45,6 +45,22 @@ public function rules(): array
...
+            'preferred_contact_method' => __('preferred contact method'),
+            'meeting_types' => __('meeting types'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualCommunicationAndConsultationPreferencesRequest.php]:
```suggestion
            'meeting_types' => __('meeting types'),
            'meeting_types.*' => __('meeting types'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 30]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'disability_and_deaf' => __('Disability and/or Deaf identity'),
+            'lived_experience_connections' => __('lived experience connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php:102]:
```suggestion
            'lived_experience_connections' => __('lived experience connections'),
            'lived_experience_connections.*' => __('lived experience connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 31]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'base_disability_type' => __('disability type'),
+            'disability_and_deaf_connections' => __('disability and deaf connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php:105]:
```suggestion
            'disability_and_deaf_connections' => __('disability and deaf connections'),
            'disability_and_deaf_connections.*' => __('disability and deaf connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 32]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'has_other_disability_connection' => __('has other disability connection'),
+            'other_disability_connection' => __('other disability connection'),
+            'area_type_connections' => __('area type connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php]:
```suggestion
            'other_disability_connection' => __('other disability connection'),
            'other_disability_connection.*' => __('other disability connection'),
            'area_type_connections' => __('area type connections'),
            'area_type_connections.*' => __('area type connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 33]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'has_indigenous_connections' => __('has indigenous connections'),
+            'indigenous_connections' => __('indigenous connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php:113]:
```suggestion
            'indigenous_connections' => __('indigenous connections'),
            'indigenous_connections.*' => __('indigenous connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 34]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'refugees_and_immigrants' => __('Refugees and/or immigrants'),
+            'has_gender_and_sexuality_connections' => __('has gender and sexuality connections'),
+            'gender_and_sexuality_connections' => __('gender and sexuality connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php:117]:
```suggestion
            'gender_and_sexuality_connections' => __('gender and sexuality connections'),
            'gender_and_sexuality_connections.*' => __('gender and sexuality connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 35]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'nb_gnc_fluid_identity' => __('Non-binary/Gender non-conforming/Gender fluid identity'),
+            'has_age_bracket_connections' => __('has age bracket connections'),
+            'age_bracket_connections' => __('age bracket connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php:121]:
```suggestion
            'age_bracket_connections' => __('age bracket connections'),
            'age_bracket_connections.*' => __('age bracket connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 36]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'has_ethnoracial_identity_connections' => __('has ethnoracial identity connections'),
+            'ethnoracial_identity_connections' => __('ethnoracial identity connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php:124]:
```suggestion
            'ethnoracial_identity_connections' => __('ethnoracial identity connections'),
            'ethnoracial_identity_connections.*' => __('ethnoracial identity connections'),
```

File: app/Http/Requests/UpdateIndividualConstituenciesRequest.php [hunk 37]
```diff
@@ -95,6 +95,33 @@ public function rules(): array
...
+            'has_other_ethnoracial_identity_connection' => __('has other ethnoracial identity connection'),
+            'other_ethnoracial_identity_connection' => __('other ethnoracial identity connection'),
+            'language_connections' => __('language connections'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualConstituenciesRequest.php]:
```suggestion
            'other_ethnoracial_identity_connection' => __('other ethnoracial identity connection'),
            'other_ethnoracial_identity_connection.*' => __('other ethnoracial identity connection'),
            'language_connections' => __('language connections'),
            'language_connections.*' => __('language connections'),
```

File: app/Http/Requests/UpdateIndividualInterestsRequest.php [hunk 38]
```diff
@@ -40,6 +40,14 @@ public function rules()
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'sectors' => __('Sectors'),
+            'impacts' => __('areas of impact'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualInterestsRequest.php]:
```suggestion
            'sectors' => __('Regulated Organization type'),
            'impacts' => __('area of accessibility planning and design'),
```

File: app/Http/Requests/UpdateIndividualRequest.php [hunk 39]
```diff
@@ -67,7 +67,15 @@ public function prepareForValidation()
     public function attributes(): array
     {
         return [
+            'name' => __('full name'),
+            'locality' => __('city or town'),
             'region' => __('province or territory'),
+            'pronouns' => __('pronouns'),
+            'bio' => __('bio'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualRequest.php:74]:
```suggestion
            'bio' => __('bio'),
            'bio.en' => __('bio (English)'),
            'bio.fr' => __('bio (French)'),
            'bio.*' => __('bio'),
```

File: app/Http/Requests/UpdateIndividualRequest.php [hunk 40]
```diff
@@ -67,7 +67,15 @@ public function prepareForValidation()
...
+            'working_languages' => __('Working languages'),
+            'consulting_services' => __('Consulting services'),
+            'social_links' => __('Social media links'),
```
Comment (jobara) [inline app/Http/Requests/UpdateIndividualRequest.php]:
```suggestion
            'consulting_services' => __('Consulting services'),
            'consulting_services.*' => __('Consulting services'),
            'social_links.*' => __('Social media links'),
```

File: app/Http/Requests/UpdateLanguagePreferencesRequest.php [hunk 41]
```diff
@@ -36,6 +36,15 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'locale' => __('locale'),
```
Comment (jobara) [inline app/Http/Requests/UpdateLanguagePreferencesRequest.php]:
```suggestion
            'locale' => __('website language'),
```

File: app/Http/Requests/UpdateLanguagePreferencesRequest.php [hunk 42]
```diff
@@ -36,6 +36,15 @@ public function rules(): array
...
+            'first_language' => __('first language'),
+            'working_languages' => __('Working languages'),
```
Comment (jobara) [inline app/Http/Requests/UpdateLanguagePreferencesRequest.php:44]:
```suggestion
            'working_languages' => __('Working languages'),
            'working_languages.*' => __('Working languages'),
```

File: app/Http/Requests/UpdateNotificationPreferencesRequest.php [hunk 43]
```diff
@@ -84,6 +84,21 @@ public function rules(): array
...
+        return [
+            'preferred_notification_method' => __('Preferred notification method'),
+            'notification_settings.consultants.channels' => __('notification settings consultants'),
+            'notification_settings.connectors.channels' => __('notification settings connectors'),
+            'notification_settings.reports.channels' => __('notification settings reports'),
+            'notification_settings.projects.channels' => __('notification settings projects'),
+            'notification_settings.projects.creators' => __('notification settings projects creators'),
+            'notification_settings.projects.types' => __('notification settings projects types'),
+            'notification_settings.projects.engagements' => __('notification settings projects engagements'),
+            'notification_settings.updates.channels' => __('notification settings updates'),
```
Comment (jobara) [inline app/Http/Requests/UpdateNotificationPreferencesRequest.php]:
```suggestion
            'notification_settings.consultants.channels' => __('Accessibility Consultant notification setting'),
            'notification_settings.consultants.channels.*' => __('Accessibility Consultant notification setting'),
            'notification_settings.connectors.channels' => __('Community Connector notification setting'),
            'notification_settings.connectors.channels.*' => __('Community Connector notification setting'),
            'notification_settings.reports.channels' => __('report notification setting'),
            'notification_settings.reports.channels.*' => __('report notification setting'),
            'notification_settings.projects.channels' => __('projects notification setting'),
            'notification_settings.projects.channels.*' => __('projects notification setting'),
            'notification_settings.projects.creators' => __('project created by organization type notification setting'),
            'notification_settings.projects.creators.*' => __('project created by organization type notification setting'),
            'notification_settings.projects.types' => __('project type notification setting'),
            'notification_settings.projects.types.*' => __('project type notification setting'),
            'notification_settings.projects.engagements' => __('project engagement type notification setting'),
            'notification_settings.projects.engagements.*' => __('project engagement type notification setting'),
            'notification_settings.updates.channels' => __('review and updates notification settings'),
            'notification_settings.updates.channels.*' => __('review and updates notification settings'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 44]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'disability_and_deaf' => __('Disability and/or Deaf identity'),
+            'lived_experience_constituencies' => __('lived experience constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:99]:
```suggestion
            'lived_experience_constituencies' => __('lived experience constituencies'),
            'lived_experience_constituencies.*' => __('lived experience constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 45]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'base_disability_type' => __('disability type'),
+            'disability_and_deaf_constituencies' => __('disability and deaf constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:102]:
```suggestion
            'disability_and_deaf_constituencies' => __('disability and deaf constituencies'),
            'disability_and_deaf_constituencies.*' => __('disability and deaf constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 46]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'has_other_disability_constituency' => __('has other disability constituency'),
+            'other_disability_constituency' => __('other disability constituency'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:105]:
```suggestion
            'other_disability_constituency' => __('other disability constituency'),
            'other_disability_constituency.*' => __('other disability constituency'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 47]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'area_type_constituencies' => __('area type constituencies'),
+            'has_indigenous_constituencies' => __('has indigenous constituencies'),
+            'indigenous_constituencies' => __('indigenous constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:110]:
```suggestion
            'indigenous_constituencies' => __('indigenous constituencies'),
            'indigenous_constituencies.*' => __('indigenous constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 48]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'refugees_and_immigrants' => __('Refugees and/or immigrants'),
+            'has_gender_and_sexuality_constituencies' => __('has gender and sexuality constituencies'),
+            'gender_and_sexuality_constituencies' => __('gender and sexuality constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:114]:
```suggestion
            'gender_and_sexuality_constituencies' => __('gender and sexuality constituencies'),
            'gender_and_sexuality_constituencies.*' => __('gender and sexuality constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 49]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'nb_gnc_fluid_identity' => __('Non-binary/Gender non-conforming/Gender fluid identity'),
+            'has_age_bracket_constituencies' => __('has age bracket constituencies'),
+            'age_bracket_constituencies' => __('age bracket constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:118]:
```suggestion
            'age_bracket_constituencies' => __('age bracket constituencies'),
            'age_bracket_constituencies.*' => __('age bracket constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 50]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'has_ethnoracial_identity_constituencies' => __('has ethnoracial identity constituencies'),
+            'ethnoracial_identity_constituencies' => __('ethnoracial identity constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:121]:
```suggestion
            'ethnoracial_identity_constituencies' => __('ethnoracial identity constituencies'),
            'ethnoracial_identity_constituencies.*' => __('ethnoracial identity constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 51]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+            'has_other_ethnoracial_identity_constituency' => __('has other ethnoracial identity constituency'),
+            'other_ethnoracial_identity_constituency' => __('other ethnoracial identity constituency'),
+            'language_constituencies' => __('language constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php]:
```suggestion
            'other_ethnoracial_identity_constituency' => __('other ethnoracial identity constituency'),
            'other_ethnoracial_identity_constituency.*' => __('other ethnoracial identity constituency'),
            'language_constituencies' => __('language constituencies'),
            'language_constituencies.*' => __('language constituencies'),
```

File: app/Http/Requests/UpdateOrganizationConstituenciesRequest.php [hunk 52]
```diff
@@ -92,6 +92,33 @@ public function rules(): array
...
+    public function attributes(): array
+    {
+        return [
+            'disability_and_deaf' => __('Disability and/or Deaf identity'),
+            'lived_experience_constituencies' => __('lived experience constituencies'),
+            'base_disability_type' => __('disability type'),
+            'disability_and_deaf_constituencies' => __('disability and deaf constituencies'),
+            'has_other_disability_constituency' => __('has other disability constituency'),
+            'other_disability_constituency' => __('other disability constituency'),
+            'area_type_constituencies' => __('area type constituencies'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationConstituenciesRequest.php:107]:
```suggestion
            'area_type_constituencies' => __('area type constituencies'),
            'area_type_constituencies.*' => __('area type constituencies'),
```

File: app/Http/Requests/UpdateOrganizationContactInformationRequest.php [hunk 53]
```diff
@@ -22,6 +22,17 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'contact_person_name' => __('Contact person'),
+            'contact_person_email' => __('Contact person’s email'),
+            'contact_person_phone' => __('Contact person’s phone number'),
+            'contact_person_vrs' => __('Contact person’s vrs'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationContactInformationRequest.php]:
```suggestion
            'contact_person_vrs' => __('Contact person requires Video Relay Service (VRS) for phone calls'),
```

File: app/Http/Requests/UpdateOrganizationInterestsRequest.php [hunk 54]
```diff
@@ -20,4 +20,12 @@ public function rules(): array
             'sectors.*' => 'exists:sectors,id',
         ];
     }
+
+    public function attributes(): array
+    {
+        return [
+            'impacts' => __('areas of impact'),
+            'sectors' => __('Sectors'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationInterestsRequest.php]:
```suggestion
            'sectors' => __('Regulated Organization type'),
            'sectors.*' => __('Regulated Organization type'),
            'impacts' => __('area of accessibility planning and design'),
            'impacts.*' => __('area of accessibility planning and design'),
```

File: app/Http/Requests/UpdateOrganizationContactInformationRequest.php [hunk 55]
```diff
@@ -22,6 +22,17 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'contact_person_name' => __('Contact person'),
+            'contact_person_email' => __('Contact person’s email'),
+            'contact_person_phone' => __('Contact person’s phone number'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationContactInformationRequest.php]: It looks like you changed the text for these. You might want to double check Figma and/or issues to make sure that they weren't that way per the design.

File: app/Http/Requests/UpdateOrganizationRequest.php [hunk 56]
```diff
@@ -82,6 +82,11 @@ public function attributes(): array
             'about.en' => __('"About your organization" (English)'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationRequest.php:82]:
```suggestion
            'about.en' => __('"About your organization" (English)'),
            'about.*' => __('"About your organization"'),
            'name.fr' => __('organization name (French)'),
            'name.en' => __('organization name (English)'),
            'name.*' => __('organization name'),
```

File: app/Http/Requests/UpdateOrganizationRequest.php [hunk 57]
```diff
@@ -82,6 +82,11 @@ public function attributes(): array
...
             'locality' => __('city or town'),
             'region' => __('province or territory'),
+            'service_areas' => __('Service areas'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationRequest.php:89]:
```suggestion
            'service_areas' => __('Service areas'),
            'service_areas.*' => __('Service areas'),
```

File: app/Http/Requests/UpdateOrganizationRequest.php [hunk 58]
```diff
@@ -82,6 +82,11 @@ public function attributes(): array
...
+            'working_languages' => __('Working languages'),
+            'consulting_services' => __('Consulting services'),
+            'social_links' => __('Social media links'),
```
Comment (jobara) [inline app/Http/Requests/UpdateOrganizationRequest.php]:
```suggestion
            'consulting_services' => __('Consulting services'),
            'consulting_services.*' => __('Consulting services'),
            'social_links' => __('Social media links'),
            'social_links.*' => __('Social media links'),
```

File: app/Http/Requests/UpdatePaymentInformationRequest.php [hunk 59]
```diff
@@ -21,6 +21,15 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'payment_types' => __('Payment type'),
```
Comment (jobara) [inline app/Http/Requests/UpdatePaymentInformationRequest.php:27]:
```suggestion
            'payment_types' => __('Payment type'),
            'payment_types.*' => __('Payment type'),
```

File: app/Http/Requests/UpdateProjectRequest.php [hunk 60]
```diff
@@ -59,8 +59,17 @@ public function rules(): array
     public function attributes(): array
     {
         return [
+            'name' => __('Project name'),
+            'goals' => __('Project goals'),
+            'scope' => __('Project scope'),
             'regions' => __('geographic areas'),
             'impacts' => __('areas of impact'),
+            'out_of_scope' => __('out of scope'),
```
Comment (jobara) [inline app/Http/Requests/UpdateProjectRequest.php]:
```suggestion
            'name.en' => __('Project name (English)'),
            'name.fr' => __('Project name (French)'),
            'name.*' => __('Project name'),
            'goals.en' => __('Project goals (English)'),
            'goals.fr' => __('Project goals (French)'),
            'goals.*' => __('Project goals'),
            'scope.en' => __('Project scope (English)'),
            'scope.fr' => __('Project scope (French)'),
            'scope' => __('Project scope'),
            'regions' => __('geographic areas'),
            'regions.*' => __('geographic areas'),
            'impacts' => __('areas of impact'),
            'impacts.*' => __('areas of impact'),
            'out_of_scope' => __('out of scope'),
            'out_of_scope.*' => __('out of scope'),
```

File: app/Http/Requests/UpdateProjectRequest.php [hunk 61]
```diff
@@ -59,8 +59,17 @@ public function rules(): array
...
+            'start_date' => __('start date'),
+            'end_date' => __('end date'),
+            'outcome_analysis' => __('Outcomes and reports'),
+            'outcomes' => __('Project outcome'),
```
Comment (jobara) [inline app/Http/Requests/UpdateProjectRequest.php]:
```suggestion
            'outcome_analysis' => __('Outcomes and reports'),
            'outcome_analysis.*' => __('Outcomes and reports'),
            'outcome_analysis_other' => __('Outcomes and reports other'),
            'outcome_analysis_other.*' => __('Outcomes and reports other'),
            'outcomes.en' => __('Project outcome (English)'),
            'outcomes.fr' => __('Project outcome (French)'),
            'outcomes.*' => __('Project outcome'),
```

File: app/Http/Requests/UpdateProjectTeamRequest.php [hunk 62]
```diff
@@ -36,10 +36,18 @@ public function rules(): array
     public function attributes(): array
     {
         return [
+            'team_size' => __('team size'),
```
Comment (jobara) [inline app/Http/Requests/UpdateProjectTeamRequest.php:39]:
```suggestion
            'team_size' => __('team size'),
            'team_size.*' => __('team size'),
```

File: app/Http/Requests/UpdateProjectTeamRequest.php [hunk 63]
```diff
@@ -36,10 +36,18 @@ public function rules(): array
...
+            'team_has_disability_or_deaf_lived_experience' => __('Our team has people with lived and living experiences of disability or being Deaf.'),
             'team_trainings.*.name' => __('training name'),
```
Comment (jobara) [inline app/Http/Requests/UpdateProjectTeamRequest.php:43]:
```suggestion
            'team_trainings' => __('training'),
            'team_trainings.*.name' => __('training name'),
```

File: app/Http/Requests/UpdateProjectTeamRequest.php [hunk 64]
```diff
@@ -36,10 +36,18 @@ public function rules(): array
...
             'team_trainings.*.date' => __('training date'),
             'team_trainings.*.trainer_name' => __('training organization or trainer name'),
             'team_trainings.*.trainer_url' => __('training organization or trainer website address'),
+            'contact_person_name' => __('Contact person'),
+            'contact_person_email' => __('Contact person’s email'),
+            'contact_person_phone' => __('Contact person’s phone number'),
+            'contact_person_vrs' => __('Contact person’s vrs'),
```
Comment (jobara) [inline app/Http/Requests/UpdateProjectTeamRequest.php]:
```suggestion
            'contact_person_vrs' => __('Contact person requires Video Relay Service (VRS) for phone calls'),
```

File: app/Http/Requests/UpdateProjectTeamRequest.php [hunk 65]
```diff
@@ -36,10 +36,18 @@ public function rules(): array
...
+            'preferred_contact_method' => __('preferred contact method'),
+            'contact_person_response_time' => __('Approximate response time'),
```
Comment (jobara) [inline app/Http/Requests/UpdateProjectTeamRequest.php:52]:
```suggestion
            'contact_person_response_time' => __('Approximate response time'),
            'contact_person_response_time.en' => __('Approximate response time (English)'),
            'contact_person_response_time.fr' => __('Approximate response time (French)'),
```

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php [hunk 66]
```diff
@@ -117,15 +117,22 @@ public function withValidator($validator)
     public function attributes(): array
     {
         return [
+            'name' => __('organization name'),
             'locality' => __('city or town'),
             'region' => __('province or territory'),
-            'contact_person_email' => __('email address'),
-            'contact_person_phone' => __('phone number'),
```
Comment (jobara) [inline app/Http/Requests/UpdateRegulatedOrganizationRequest.php:123]: Please review Figma and/or issues to see if this was a specific design requirement.

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php [hunk 67]
```diff
@@ -117,15 +117,22 @@ public function withValidator($validator)
     public function attributes(): array
     {
         return [
+            'name' => __('organization name'),
```
Comment (jobara) [inline app/Http/Requests/UpdateRegulatedOrganizationRequest.php]:
```suggestion
            'name.en' => __('organization name (English)'),
            'name.fr' => __('organization name (French)'),
            'name.*' => __('organization name'),
```

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php [hunk 68]
```diff
@@ -117,15 +117,22 @@ public function withValidator($validator)
...
             'locality' => __('city or town'),
             'region' => __('province or territory'),
-            'contact_person_email' => __('email address'),
-            'contact_person_phone' => __('phone number'),
+            'service_areas' => __('Service areas'),
+            'sectors' => __('Sectors'),
```
Comment (jobara) [inline app/Http/Requests/UpdateRegulatedOrganizationRequest.php]:
```suggestion
            'service_areas' => __('Service areas'),
            'service_areas.*' => __('Service areas'),
            'sectors' => __('type of Regulated Organization'),
```

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php [hunk 69]
```diff
@@ -117,15 +117,22 @@ public function withValidator($validator)
...
             'about.fr' => __('"About your organization" (French)'),
             'about.en' => __('"About your organization" (English)'),
```
Comment (jobara) [inline app/Http/Requests/UpdateRegulatedOrganizationRequest.php:129]:
```suggestion
            'about.en' => __('"About your organization" (English)'),
            'about.*' => __('"About your organization" (English)'),
```

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php [hunk 70]
```diff
@@ -117,15 +117,22 @@ public function withValidator($validator)
...
             'accessibility_and_inclusion_links.*.title' => __('accessibility and inclusion link title'),
             'accessibility_and_inclusion_links.*.url' => __('accessibility and inclusion link'),
-            'social_links.*.active_url' => __(''),
+            'social_links' => __('Social media links'),
```
Comment (jobara) [inline app/Http/Requests/UpdateRegulatedOrganizationRequest.php]:
```suggestion
            'social_links.*' => __('Social media links'),
```

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php [hunk 71]
```diff
@@ -117,15 +117,22 @@ public function withValidator($validator)
...
+            'website_link' => __('Website link'),
+            'contact_person_name' => __('Contact person'),
+            'contact_person_email' => __('Contact person’s email'),
+            'contact_person_phone' => __('Contact person’s phone number'),
+            'contact_person_vrs' => __('Contact person’s vrs'),
```
Comment (jobara) [inline app/Http/Requests/UpdateRegulatedOrganizationRequest.php]:
```suggestion
            'contact_person_vrs' => __('Contact person requires Video Relay Service (VRS) for phone calls'),
```

File: app/Http/Requests/UpdateWebsiteAccessibilityPreferencesRequest.php [hunk 72]
```diff
@@ -20,4 +20,12 @@ public function rules(): array
             'text_to_speech' => 'required|boolean',
         ];
     }
+
+    public function attributes(): array
+    {
+        return [
+            'theme' => __('Theme'),
```
Comment (jobara) [inline app/Http/Requests/UpdateWebsiteAccessibilityPreferencesRequest.php]:
```suggestion
            'theme' => __('Contrast adjustment'),
```

**Review by jobara — CHANGES_REQUESTED** [review]
It looks like you missed doing AcceptInvitationRequest. It looks like the only attribute there is `email`.

File: app/Http/Requests/StoreDefinedTermRequest.php (hunk 5 above)
Comment (chosww) [reply app/Http/Requests/StoreDefinedTermRequest.php:32]: It doesn't seems like it, though I think this may be used later? We should confirm with @greatislander

File: app/Http/Requests/StoreProjectContextRequest.php (hunk 9 above)
Comment (chosww) [reply app/Http/Requests/StoreProjectContextRequest.php:26]: We currently use both terms previous project and original project in other messages, and there are 2 usages of previous project, and one usage of original project. I think we should always be consistent throughout the messages.

File: app/Http/Requests/UpdateAreasOfInterestRequest.php (hunk 15 above)
Comment (chosww) [reply app/Http/Requests/UpdateAreasOfInterestRequest.php]: Are all sectors regulated organization types? We already have translations for both sectors and impacts, and those are used commonly throughout the requests attributes.

File: app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php (hunk 16 above)
Comment (chosww) [reply app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php]: We have translations for "My support ...."s, and I think it makes sense to use word "my" in front of support person.

File: app/Http/Requests/UpdateDefinedTermRequest.php (hunk 18 above)
Comment (chosww) [reply app/Http/Requests/UpdateDefinedTermRequest.php:32]: This one is not used either, but we should ask @greatislander about this one too

File: app/Http/Requests/UpdateOrganizationContactInformationRequest.php (hunk 55 above)
Comment (chosww) [reply app/Http/Requests/UpdateOrganizationContactInformationRequest.php]: oh, I just used ones those already have French translations.

File: app/Http/Requests/UpdateRegulatedOrganizationRequest.php (hunk 66 above)
Comment (chosww) [reply app/Http/Requests/UpdateRegulatedOrganizationRequest.php:123]: Oh, I see what you meant by the previous comment. I did change these to the translations we have that suits the context. There was no specific design requirement about these, so I will revert back to what it was.

File: app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php (hunk 16 above)
Comment (chosww) [reply app/Http/Requests/UpdateCommunicationAndConsultationPreferencesRequest.php]: But now I think about it, your suggestions make more sense, even though we will need extra translations. I will update it based on your suggestions.

File: app/Http/Requests/UpdateAreasOfInterestRequest.php (hunk 15 above)
Comment (chosww) [reply app/Http/Requests/UpdateAreasOfInterestRequest.php]: I see that you have these update suggestions for all the cases, so I will update them based on your suggestions.

File: app/Http/Requests/UpdateEngagementRequest.php (hunk 21 above)
Comment (chosww) [reply app/Http/Requests/UpdateEngagementRequest.php]: Should we also update these to 'Ways to attend' ?

File: app/Http/Requests/StoreProjectContextRequest.php (hunk 9 above)
Comment (jobara) [reply app/Http/Requests/StoreProjectContextRequest.php:26]: If they are used for the same purpose, I'd agree that they should be consistent.

File: app/Http/Requests/UpdateAreasOfInterestRequest.php (hunk 15 above)
Comment (jobara) [reply app/Http/Requests/UpdateAreasOfInterestRequest.php]: Thanks. I believe the contents of these sections changed at some point, so they probably don't align as well with the model names as they once did.

File: app/Http/Requests/UpdateEngagementRequest.php (hunk 21 above)
Comment (jobara) [reply app/Http/Requests/UpdateEngagementRequest.php]: Yah, I think makes sense. Thanks for catching it.

**Comment by jobara** [comment]
> It looks like you missed doing AcceptInvitationRequest. It looks like the only attribute there is `email`.

I think this one is still missing. It's being done through `withValidator()`.

**Comment by chosww** [comment]
@jobara this PR is ready for another review, thanks!

File: app/Http/Requests/DestroyUserRequest.php [hunk 73]
```diff
@@ -26,6 +26,13 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'current_password' => __('current password'),
```
Comment (jobara) [inline app/Http/Requests/DestroyUserRequest.php:32]: I think we need to add `organizations` which is being checked in the `withValidator` function.

File: app/Http/Requests/AcceptInvitationRequest.php [hunk 74]
```diff
@@ -22,6 +22,13 @@ public function rules(): array
         return [];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'email' => __('email address'),
```
Comment (jobara) [inline app/Http/Requests/AcceptInvitationRequest.php:28]: I notice in at least one other location that we've used `__('email')` instead. If it makes sense, can we make these consistent?

File: app/Http/Requests/StoreOrganizationRequest.php [hunk 75]
```diff
@@ -22,6 +22,13 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'type' => __('organization type'),
```
Comment (jobara) [inline app/Http/Requests/StoreOrganizationRequest.php:28]: Missing attributes for `name.en` and `name.fr`.

File: app/Http/Requests/StoreOrganizationTypeRequest.php [hunk 76]
```diff
@@ -28,6 +28,15 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
+            'type' => __('organization type'),
+            'name.en' => __('organization name (English)'),
+            'name.fr' => __('organization name (French)'),
```
Comment (jobara) [inline app/Http/Requests/StoreOrganizationTypeRequest.php]: These don't appear to be required here. Perhaps they were added to the wrong file.

File: app/Http/Requests/UpdateAccessNeedsRequest.php [hunk 77]
```diff
@@ -160,6 +160,32 @@ public function withValidator(Validator $validator)
...
     }
 
+    public function attributes(): array
+    {
+        return [
+            'general_access_needs' => __('General access needs'),
+            'general_access_needs.*' => __('General access needs'),
+            'other' => __('other'),
+            'other_access_need' => __('other access need'),
+            'meeting_access_needs' => __('meeting access needs'),
```
Comment (jobara) [inline app/Http/Requests/UpdateAccessNeedsRequest.php:170]: Missing `'meeting_access_needs.*'`

File: app/Http/Requests/UpdateDefinedTermRequest.php [hunk 78]
```diff
@@ -28,4 +28,12 @@ public function rules()
...
+    {
+        return [
+            'term' => __('term'),
+            'definition' => __('definition'),
```
Comment (jobara) [inline app/Http/Requests/UpdateDefinedTermRequest.php]: Missing `'term.*'` and `'definition.*'`.

File: app/Http/Requests/UpdateNotificationPreferencesRequest.php [hunk 79]
```diff
@@ -84,6 +84,28 @@ public function rules(): array
         ];
     }
 
+    public function attributes(): array
+    {
+        return [
```
Comment (jobara) [inline app/Http/Requests/UpdateNotificationPreferencesRequest.php:89]: Missing `'preferred_notification_method'`.

**Review by jobara — CHANGES_REQUESTED** [review]
@chosww could you also re-run `composer localize`?

File: app/Http/Requests/DestroyUserRequest.php [hunk 80]
```diff
@@ -30,6 +30,7 @@ public function attributes(): array
     {
         return [
             'current_password' => __('current password'),
+            'organization' => __('organization'),
```
Comment (jobara) [inline app/Http/Requests/DestroyUserRequest.php]: I believe this is supposed to be `'organizations'`.

File: app/Http/Requests/StoreEngagementLanguagesRequest.php [hunk 81]
```diff
@@ -21,4 +21,11 @@ public function rules(): array
             ],
         ];
     }
+
+    public function attributes(): array
+    {
+        return [
+            'languages' => __('languages'),
```
Comment (jobara) [inline app/Http/Requests/StoreEngagementLanguagesRequest.php:28]: Missing `'languages.*'`

**Review by jobara — CHANGES_REQUESTED** [review]

**Review by jobara — CHANGES_REQUESTED** [review]
@chosww could you please run `composer localize` again. I think that's all that's left.

**Review by jobara — APPROVED** [review]
